In [1]:
def increment(n):
    n += 1
    return n

n = 1
while n < 10:
    n = increment(n)
print(n)

10


In [ ]:
class NewList(list):
    def remove_max(self):
        self.remove(max(self))
    def append_sum(self):
        self.append(sum(self))
        
x = NewList([1,2,3])
while max(x) < 10:
    x.remove_max()
    x.append_sum()
    
print(x)

In [3]:
import numpy as np

In [9]:
x = np.array([[3,6],[5,7]])
y = x.transpose()
print(y)

[[3 5]
 [6 7]]


In [10]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [18]:
z = np.array([1,2,5])

In [19]:
z[1:2]

array([2])

In [21]:
a = np.array([1,2])
b = np.array([3,4,5])
b[a]

array([4, 5])

In [22]:
c = b[1:]
b[a] is c

False

In [24]:
x = 20
not np.any([x%i == 0 for i in range(2,x)])

False